Router.configure({
    layoutTemplate: "main_layout"
});

Router.map(function(){
    //page1
    this.route("home",{
        path:["/","/home"],
        template:"home"
    });

    //page2
    this.route("page2",{
        path:"/page2",
        template:"page2"
    });
    //page2
    this.route("page3",{
        path:"/page3",
        template:"page3"
    });
    //page2
    this.route("page4",{
        path:"/page4",
        template:"page4"
    });
    //page2
    this.route("page5",{
        path:"/page5",
        template:"page5"
    });
    //page2
    this.route("login",{
        path:"/login",
        template:"login"
    });
    //page2
    this.route("signup",{
        path:"/signup",
        template:"signup"
    });
    //profile
    this.route("profile",{
        path:"/profile",
        template:"profile"
    });
});